server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  profiles:
    group:
      dev: "dev,env"
    active: dev

  jpa:
    show-sql: false
    open-in-view: false

    properties:
      hibernate:
        show_sql: false